#ifndef SLEEP_APNEA_METRICS_H__		
#define SLEEP_APNEA_METRICS_H__

enum SleepApneaMetrics {
	PCA_CZEBYSZEW_METRICS,
	PCA_MANHATTAN_MATRICS,
	PCA_EUCLIDEAN_METRICS
};

#endif // SLEEP_APNEA_METRICS_H__