# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ekg.h
SOURCES += ./ekg.cpp \
    ./main.cpp
FORMS += ./ekg.ui
RESOURCES += ekg.qrc
